### ISSUE TITLE
pythonIoc issues with EPICS Base 7.0.3

### ISSUE THREAD

**Issue by ZohebShaikh** [dls-controls/pythonIoc#4] opened 2020-09-14 15:19 UTC
These are the errors I get when I run examples/runtest 

```
Starting iocInit
############################################################################
## EPICS R7.0.3
## EPICS Base built Aug 26 2020
############################################################################
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 14
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 14
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 14
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 14
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 14
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 14
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 14
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 241, in LookupRecord
    return cls._RecordDirectory[name]
KeyError: 94101980930144
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 241, in LookupRecord
    return cls._RecordDirectory[name]
KeyError: 94101980923072
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 241, in LookupRecord
    return cls._RecordDirectory[name]
KeyError: 94101980937792
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 241, in LookupRecord
    return cls._RecordDirectory[name]
KeyError: 94101980920832
Error (514,514) PV: TS-DI-TEST-01:AO ao: init_record

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 241, in LookupRecord
    return cls._RecordDirectory[name]
KeyError: 94101980934768
Error (514,514) PV: TS-DI-TEST-01:SINP ao: init_record

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 14
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 241, in LookupRecord
    return cls._RecordDirectory[name]
KeyError: 94101980925504
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 241, in LookupRecord
    return cls._RecordDirectory[name]
KeyError: 94101980933376
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 14
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 185, in _init_record
    self = cls.LookupRecord(getattr(record, cls._link_))
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 14
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 145, in <lambda>
    cls.__call_instance_method(method, args, record_offset)
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 157, in __call_instance_method
    self = record.DPVT
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 17
PV: TS-DI-TEST-01:STRINGIN scanAdd: I/O Intr not valid

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 145, in <lambda>
    cls.__call_instance_method(method, args, record_offset)
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 157, in __call_instance_method
    self = record.DPVT
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 17
PV: TS-DI-TEST-01:LONGSTRING scanAdd: I/O Intr not valid

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 145, in <lambda>
    cls.__call_instance_method(method, args, record_offset)
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 157, in __call_instance_method
    self = record.DPVT
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 17
PV: TS-DI-TEST-01:SIN scanAdd: I/O Intr not valid

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 145, in <lambda>
    cls.__call_instance_method(method, args, record_offset)
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 157, in __call_instance_method
    self = record.DPVT
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 17
PV: TS-DI-TEST-01:WAVEFORM scanAdd: I/O Intr not valid

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 145, in <lambda>
    cls.__call_instance_method(method, args, record_offset)
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 157, in __call_instance_method
    self = record.DPVT
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 17
PV: TS-DI-TEST-01:WAVEFORM2 scanAdd: I/O Intr not valid

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 145, in <lambda>
    cls.__call_instance_method(method, args, record_offset)
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 157, in __call_instance_method
    self = record.DPVT
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 17
PV: TS-DI-TEST-01:BOOLIN scanAdd: I/O Intr not valid

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 145, in <lambda>
    cls.__call_instance_method(method, args, record_offset)
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 157, in __call_instance_method
    self = record.DPVT
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 17
PV: TS-DI-TEST-01:LONGIN scanAdd: I/O Intr not valid

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 145, in <lambda>
    cls.__call_instance_method(method, args, record_offset)
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 157, in __call_instance_method
    self = record.DPVT
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 17
PV: TS-DI-TEST-01:AI scanAdd: I/O Intr not valid

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 145, in <lambda>
    cls.__call_instance_method(method, args, record_offset)
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 157, in __call_instance_method
    self = record.DPVT
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 17
PV: TS-DI-TEST-01:MBBI scanAdd: I/O Intr not valid

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 145, in <lambda>
    cls.__call_instance_method(method, args, record_offset)
  File "/usr/local/epics7New/pythonIoc/python/softioc/device_core.py", line 157, in __call_instance_method
    self = record.DPVT
  File "/usr/local/epics7New/pythonIoc/python/softioc/fields.py", line 153, in __getattr__
    ctypes_type = DbfCodeToCtypes[field_type]
KeyError: 17
iocRun: All initialization complete
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
```

**Comment by Araneidae** [comment] 2021-06-28 11:52
Unable to reproduce, but believe this resolved by #5.

**Closed by Araneidae** 2021-06-28 11:52 UTC
